<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'hypeJunction\\' => array($baseDir . '/classes/hypeJunction', $vendorDir . '/hypejunction/cmp-lists/classes', $vendorDir . '/hypejunction/cmp-util/classes/hypeJunction'),
    'UFCOE\\' => array($baseDir . '/classes/UFCOE', $vendorDir . '/hypejunction/cmp-util/classes/UFCOE'),
);
