<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'hypeJunction\\' => array($vendorDir . '/hypejunction/cmp-util/classes/hypeJunction', $vendorDir . '/hypejunction/cmp-lists/classes'),
    'UFCOE\\' => array($vendorDir . '/hypejunction/cmp-util/classes/UFCOE'),
);
